# Generated by Django 5.2.6 on 2025-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profilemodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='cover_position',
            field=models.CharField(choices=[('center', 'По центру'), ('top', 'Верх'), ('bottom', 'Низ'), ('left', 'Лево'), ('right', 'Право')], default='center', max_length=20),
        ),
    ]
