# Generated by Django 5.2.6 on 2025-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profilemodel_cover_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='cover_position',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
