# Generated by Django 5.2.6 on 2025-09-25 16:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.JSONField(default=list)),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=450, verbose_name='Описание')),
                ('habit_type', models.CharField(choices=[('useful', 'Полезная'), ('harmful', 'Вредная')], max_length=10, verbose_name='Тип привычки')),
                ('category', models.CharField(choices=[('health', 'Здоровье'), ('sport', 'Спорт'), ('learning', 'Обучение'), ('productivity', 'Продуктивность'), ('finance', 'Финансы'), ('relationships', 'Отношения'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('reminder_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Время выполнения')),
                ('duration_minutes', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)], verbose_name='Длительность (минуты)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['created_at'],
            },
        ),
    ]
