# Generated by Django 5.2.6 on 2025-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='days_of_week',
            field=models.JSONField(default=list, verbose_name='Дни недели'),
        ),
    ]
