# Generated by Django 5.2.6 on 2025-11-11 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habitmodel_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущая серия'),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='last_completed',
            field=models.DateField(blank=True, null=True, verbose_name='Последнее выполнение'),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='success_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Процент успеха'),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='total_completions',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего выполнений'),
        ),
        migrations.AddField(
            model_name='habitmodel',
            name='total_time_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее время (минуты)'),
        ),
    ]
