# Generated by Django 5.2.6 on 2025-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habitmodel_current_streak_habitmodel_last_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitmodel',
            name='category',
            field=models.CharField(choices=[('health', 'Здоровье'), ('sport', 'Спорт'), ('learning', 'Образование'), ('relationships', 'Отношения'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
