# Generated by Django 5.2.6 on 2025-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habitmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitmodel',
            name='best_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Лучшая серия'),
        ),
    ]
