# Generated by Django 5.2.6 on 2025-11-30 22:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habitmodel_best_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCompletionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateField(default=datetime.date.today, verbose_name='Дата выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habitmodel')),
            ],
            options={
                'verbose_name': 'Выполнение привычки',
                'verbose_name_plural': 'Выполнения привычек',
            },
        ),
    ]
