# Generated by Django 5.2.6 on 2025-11-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habitcompletionmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletionmodel',
            unique_together={('habit', 'completed_at')},
        ),
    ]
