# Generated by Django 5.2.6 on 2025-11-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_remove_telegramuser_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
