# Generated by Django 5.2.6 on 2025-11-25 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_tguser_message_delete_telegramuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='context',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='django_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
