# Generated by Django 5.2.6 on 2025-11-25 19:53

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_alter_tguser_options_remove_tguser_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=django_fsm.FSMField(default='start', max_length=50, protected=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='temp_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
