# Generated by Django 5.2.6 on 2025-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_tguser_state_tguser_temp_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='state',
        ),
    ]
