# Generated by Django 5.2.6 on 2025-11-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0009_remove_tguser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='auth_step',
            field=models.CharField(choices=[('idle', 'Ожидание'), ('waiting_username', 'Ожидает логин'), ('waiting_password', 'Ожидает пароль')], default='idle', max_length=20),
        ),
    ]
